server:
  port: 9090
  servlet:
    encoding:
      force-response: true


spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/otest
    username: root
    password: 1234
  profiles:
    include: oauth
  session:
    jdbc:
      initialize-schema: always


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id : 309858913704-6halfhtqh3045mgq09ljeki2rggnv4ft.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:9090/login/oauth2/code/google"
            scope: profile,email
          kakao:
            authorization-grant-type: authorization_code
            client-id : 145ebba4f7074f9ce47312cb5270f459
            client-secret : Pr7RkuivpvitO7sESQBabmhT9q6IfoET
            redirect-uri: "http://localhost:9090/login/oauth2/code/kakao"
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
logging:
  level:
    org:
      springframework: debug